#+TITLE: Tmux git status

Enables displaying git status in status-left or status-right.

* Installation

** Installation with [Tmux Plugin Manager](https://github.com/tmux-plugins/tpm) (recommended)
Add plugin to the list of TPM plugins in =.tmux.conf=:

#+begin_src text
  set -g @plugin 'yygcode/tmux-git'
#+end_src

Hit =<prefix> + I= to fetch the plugin and source it.

If format strings are added to =status-right=, they should now be visible.

** Manual Installation
Clone the repo:
#+begin_src sh
  git clone https://github.com/yygcode/tmux-git ~/clone/path
#+end_src

Add this line to the bottom of =.tmux.conf=:

#+begin_src text
  run-shell ~/clone/path/git.tmux
#+end_src

From the terminal, reload TMUX environment:

#+begin_src sh
  tmux source-file ~/.tmux.conf
#+end_src

If format strings are added to =status-right=, they should now be visible.

* Usage

Add any of the supported format strings (see below) to the =status-right= tmux
option in =.tmux.conf=. Example:

#+begin_src text
  set -g status-right 'Git:#[fg=green]#{git_branch}[#{git_commit}#{git_dirty}]'
#+end_src

** Supported Format Strings
- =#{git_branch}=: Current git branch
- =#{git_commit}=: abbreviated commit hash
- =#{git_dirty}=: Empty if clean, otherwise show "-dirty"

** Test
#+begin_src sh
  tmux set -g status-right 'Git:#[fg=green]#{git_branch}[#{git_commit}#{git_dirty}]'
  tmux run ~/clone/path/git.tmux
#+end_src

* License
No Rights Reserved.
